import type { TicketDto } from "../model/ticket.types";

export const mockTicketDtos: TicketDto[] = [
  {
    id: "TCK-1001",
    title: "Cannot connect to VPN",
    requester: "Anna Petrova",
    status: "new",
    priority: "high",
    updatedAt: "2026-04-23T13:40:00.000Z",
    description: "VPN client fails after password rotation.",
  },
  {
    id: "TCK-1002",
    title: "Printer queue is stuck",
    requester: "Pavel Smirnov",
    status: "in-progress",
    priority: "medium",
    updatedAt: "2026-04-23T11:10:00.000Z",
    description: "Shared printer accepts jobs but nothing is printed.",
  },
  {
    id: "TCK-1003",
    title: "Laptop replacement approval",
    requester: "Maria Volkova",
    status: "reviewed",
    priority: "low",
    updatedAt: "2026-04-22T17:25:00.000Z",
    description: "Manager approved laptop replacement.",
  },
  {
    id: "TCK-1004",
    title: "Email archive export",
    requester: "Denis Orlov",
    status: "new",
    priority: "medium",
    updatedAt: "2026-04-22T15:05:00.000Z",
    description: "Requester needs an archive export for legal review.",
  },
  {
    id: "TCK-1005",
    title: "New hire account setup",
    requester: "Elena Morozova",
    status: "in-progress",
    priority: "high",
    updatedAt: "2026-04-22T12:15:00.000Z",
    description: "Account setup is blocked on group membership validation.",
  },
  {
    id: "TCK-1006",
    title: "Access to finance share",
    requester: "Kirill Sokolov",
    status: "new",
    priority: "medium",
    updatedAt: "2026-04-21T18:45:00.000Z",
    description: "User requests read access to finance reporting folder.",
  },
  {
    id: "TCK-1007",
    title: "Video call audio issue",
    requester: "Olga Ivanova",
    status: "reviewed",
    priority: "low",
    updatedAt: "2026-04-21T16:20:00.000Z",
    description: "Headset microphone is detected but produces no audio.",
  },
  {
    id: "TCK-1008",
    title: "CRM profile duplicate",
    requester: "Roman Kuznetsov",
    status: "in-progress",
    priority: "medium",
    updatedAt: "2026-04-21T10:30:00.000Z",
    description: "Two CRM profiles exist for the same employee.",
  },
  {
    id: "TCK-1009",
    title: "Mobile device enrollment",
    requester: "Irina Lebedeva",
    status: "new",
    priority: "low",
    updatedAt: "2026-04-20T14:35:00.000Z",
    description: "Corporate phone cannot complete MDM enrollment.",
  },
  {
    id: "TCK-1010",
    title: "Database client license",
    requester: "Sergey Fedorov",
    status: "new",
    priority: "high",
    updatedAt: "2026-04-20T09:50:00.000Z",
    description: "Engineer needs access to an approved database client.",
  },
];
